baseurl = "https://iyarlin.github.io/"
languageCode = "en-us"
title = "Just be-cause"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "just-be-cause"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/IyarLin"

[params]
    description = "Hands on Causal inference and general ML"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "images/favicon.ico"

    [params.logo]
    url = "home_button.png"
    width = 100
    height = 100
    alt = "Logo"

